### ISSUE TITLE
Arduino Yubico OTP not working?

### ISSUE THREAD

**Issue by lostpackets** [pagong/arduino2-yksim#2]
Hello,
I have tried to use the OTP from this repo and I flashed it to my arduino pro micro successfully. But I am not sure if the arduino yk simulator should work like an official yubikey OTP.
From my experience, none of the codes work when I try to verify them using Yubico's official otp verify website.
Is the arduino2-yksim intended to only simulate yubikey's way of creating otp codes, or are the codes supposed to work as if they were OTP codes from Yubico?
Will you please clarify as to why this is? Thank you.
https://demo.yubico.com/otp/verify

**Comment by pagong** [comment]
Thank you for trying this little project, which does only simulate an Yubikey OTP key. (and not a TOTP key!)
As you have defined your own key material, the Yubico site has no idea how to verify the codes of the simulator.

You can either search and install an open-source Yubikey validator to verify the codes.
For example: https://github.com/bastianraschke/ardukey-auth-server
 
Or you could try to register your simulator with Yubico's validator in the cloud. 
But since the YK simulator is not a true YubiKey, this might not work at all.

**Comment by pagong** [comment]
Closing the issue, as there has been no further feedback from @lostpackets
